# ================================================================
# Shared statistics helpers for behavioral dynamics analyses
# MMMSociability
# ================================================================
# Provides compact group summaries and CON/RES/SUS pairwise contrasts
# for outputs generated by the multiscale behavioral dynamics scripts.
# ================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(purrr)
  library(tibble)
})

PREFERRED_GROUP_LEVELS <- c("CON", "RES", "SUS")
PRIMARY_CONTRASTS <- c("SUS-CON", "SUS-RES")

cohens_d_pooled <- function(x, y) {
  x <- x[is.finite(x)]
  y <- y[is.finite(y)]
  if (length(x) < 2 || length(y) < 2) return(NA_real_)
  vx <- stats::var(x)
  vy <- stats::var(y)
  sp <- sqrt(((length(x) - 1) * vx + (length(y) - 1) * vy) / (length(x) + length(y) - 2))
  if (!is.finite(sp) || sp == 0) return(NA_real_)
  (mean(y) - mean(x)) / sp
}

safe_welch_test <- function(x, y) {
  x <- x[is.finite(x)]
  y <- y[is.finite(y)]
  if (length(x) < 2 || length(y) < 2 || (sd(x) == 0 && sd(y) == 0)) {
    return(tibble(estimate = NA_real_, statistic = NA_real_, p.value = NA_real_, conf.low = NA_real_, conf.high = NA_real_))
  }
  tt <- try(stats::t.test(y, x), silent = TRUE)
  if (inherits(tt, "try-error")) {
    return(tibble(estimate = NA_real_, statistic = NA_real_, p.value = NA_real_, conf.low = NA_real_, conf.high = NA_real_))
  }
  tibble(
    estimate = unname(mean(y, na.rm = TRUE) - mean(x, na.rm = TRUE)),
    statistic = unname(tt$statistic),
    p.value = tt$p.value,
    conf.low = unname(tt$conf.int[1]),
    conf.high = unname(tt$conf.int[2])
  )
}

normalise_group_levels <- function(dat, group_col = "Group") {
  if (!group_col %in% names(dat)) return(dat)
  dat %>%
    mutate(
      Group = as.character(.data[[group_col]]),
      Group = factor(Group, levels = unique(c(PREFERRED_GROUP_LEVELS, sort(unique(Group)))))
    )
}

make_dynamics_group_summary <- function(dat,
                                        value_cols,
                                        group_cols = c("BinLevel", "ProximityInput", "Metric", "Phase", "CageChange", "Sex", "Group"),
                                        animal_col = "AnimalNum") {
  if (nrow(dat) == 0) return(tibble())
  value_cols <- intersect(value_cols, names(dat))
  group_cols <- intersect(group_cols, names(dat))
  if (length(value_cols) == 0) return(tibble())

  dat %>%
    pivot_longer(cols = all_of(value_cols), names_to = "Outcome", values_to = "Value") %>%
    group_by(across(all_of(group_cols)), Outcome) %>%
    summarise(
      n_animals = if (animal_col %in% names(cur_data())) n_distinct(.data[[animal_col]]) else n(),
      n_obs = sum(is.finite(Value)),
      mean = mean(Value, na.rm = TRUE),
      sd = sd(Value, na.rm = TRUE),
      sem = sd / sqrt(n_obs),
      median = median(Value, na.rm = TRUE),
      q25 = quantile(Value, 0.25, na.rm = TRUE, names = FALSE),
      q75 = quantile(Value, 0.75, na.rm = TRUE, names = FALSE),
      .groups = "drop"
    )
}

make_dynamics_group_contrasts <- function(dat,
                                          value_cols,
                                          by_cols = c("BinLevel", "ProximityInput", "Metric", "Phase", "CageChange", "Sex"),
                                          min_n_per_group = 2) {
  if (nrow(dat) == 0 || !"Group" %in% names(dat)) return(tibble())
  value_cols <- intersect(value_cols, names(dat))
  by_cols <- intersect(by_cols, names(dat))
  if (length(value_cols) == 0) return(tibble())

  pairs <- list(c("CON", "RES"), c("CON", "SUS"), c("RES", "SUS"))

  long <- dat %>%
    normalise_group_levels() %>%
    pivot_longer(cols = all_of(value_cols), names_to = "Outcome", values_to = "Value") %>%
    filter(is.finite(Value), !is.na(Group), as.character(Group) != "All")

  if (nrow(long) == 0) return(tibble())

  split_cols <- c(by_cols, "Outcome")

  long %>%
    group_by(across(all_of(split_cols))) %>%
    group_modify(~{
      d <- .x
      map_dfr(pairs, function(pair) {
        ref <- pair[1]
        comp <- pair[2]
        x <- d$Value[as.character(d$Group) == ref]
        y <- d$Value[as.character(d$Group) == comp]
        n_ref <- sum(is.finite(x))
        n_comp <- sum(is.finite(y))
        base <- tibble(
          contrast = paste0(comp, "-", ref),
          group_ref = ref,
          group_comp = comp,
          n_ref = n_ref,
          n_comp = n_comp,
          mean_ref = mean(x, na.rm = TRUE),
          mean_comp = mean(y, na.rm = TRUE)
        )
        if (n_ref < min_n_per_group || n_comp < min_n_per_group) {
          return(base %>% mutate(
            estimate = NA_real_, statistic = NA_real_, p.value = NA_real_,
            conf.low = NA_real_, conf.high = NA_real_, cohen_d = NA_real_,
            status = "skipped_low_n"
          ))
        }
        safe_welch_test(x, y) %>%
          bind_cols(base) %>%
          mutate(cohen_d = cohens_d_pooled(x, y), status = "tested") %>%
          select(contrast, group_ref, group_comp, n_ref, n_comp, mean_ref, mean_comp,
                 estimate, statistic, p.value, conf.low, conf.high, cohen_d, status)
      })
    }) %>%
    ungroup() %>%
    group_by(across(all_of(split_cols))) %>%
    mutate(
      p.adjust_bh_family = p.adjust(p.value, method = "BH"),
      p.adjust_holm_family = p.adjust(p.value, method = "holm"),
      is_primary_contrast = contrast %in% PRIMARY_CONTRASTS,
      p.adjust_bh_primary = {
        out <- rep(NA_real_, n())
        idx <- is_primary_contrast %in% TRUE
        out[idx] <- p.adjust(p.value[idx], method = "BH")
        out
      },
      p.sign = case_when(
        is.na(p.adjust_bh_family) ~ NA_character_,
        p.adjust_bh_family < 0.001 ~ "***",
        p.adjust_bh_family < 0.01 ~ "**",
        p.adjust_bh_family < 0.05 ~ "*",
        p.adjust_bh_family < 0.10 ~ "†",
        TRUE ~ "ns"
      ),
      p.sign_primary = case_when(
        is.na(p.adjust_bh_primary) ~ NA_character_,
        p.adjust_bh_primary < 0.001 ~ "***",
        p.adjust_bh_primary < 0.01 ~ "**",
        p.adjust_bh_primary < 0.05 ~ "*",
        p.adjust_bh_primary < 0.10 ~ "†",
        TRUE ~ "ns"
      )
    ) %>%
    ungroup()
}

write_dynamics_statistics <- function(dat,
                                      output_dir,
                                      analysis_name,
                                      value_cols,
                                      by_cols = c("BinLevel", "ProximityInput", "Metric", "Phase", "CageChange", "Sex"),
                                      summary_group_cols = c("BinLevel", "ProximityInput", "Metric", "Phase", "CageChange", "Sex", "Group")) {
  if (!exists("write_table")) {
    stop("write_table() not found. Source Functions/behavioral_dynamics_helpers.R first.", call. = FALSE)
  }
  if (nrow(dat) == 0) return(invisible(NULL))

  summary_tbl <- make_dynamics_group_summary(dat, value_cols = value_cols, group_cols = summary_group_cols)
  contrast_tbl <- make_dynamics_group_contrasts(dat, value_cols = value_cols, by_cols = by_cols)

  write_table(summary_tbl, file.path(output_dir, "tables", paste0(analysis_name, "_group_summary.csv")))
  write_table(contrast_tbl, file.path(output_dir, "tables", paste0(analysis_name, "_group_contrasts.csv")))

  invisible(list(summary = summary_tbl, contrasts = contrast_tbl))
}
