# ================================================================
# Dynamic Social Network Analysis
# MMMSociability
# ================================================================
# Goal:
#   Convert proximity / interaction data into time-resolved social-network
#   summaries suitable for stress-resilience analyses.
#
# Two supported input formats:
#   A) animal-level table with normalized proximity per animal x time bin
#      -> estimates social connectedness / fragmentation per animal-period
#   B) dyadic table generated by Analysis/05_build_dyadic_rfid_contacts.R
#      -> computes true graph/network metrics
#
# Recommended scale:
#   1–5 min bins for dynamic networks. Default is 5min_based.
# ================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(readr)
  library(stringr)
  library(purrr)
  library(tibble)
})

source("Functions/behavioral_dynamics_helpers.R")

# ------------------------------------------------
# USER INPUT
# ------------------------------------------------

bin_level <- "5min_based"
input_file <- file.path("analysis_ready/03_derived_metrics", bin_level, "all_behavior_metrics.csv")
output_dir <- file.path("analysis_ready/06_behavioral_dynamics/social_networks", bin_level)

# True dyadic RFID contact file generated by Analysis/05_build_dyadic_rfid_contacts.R.
# This older dyadic file may not be multiscale unless that script was run with
# the corresponding bin size. If absent, animal-level social dynamics are still written.
dyad_file <- "analysis_ready/06_behavioral_dynamics/dyadic_contacts/tables/dyadic_network_ready.csv"

# Animal-level proximity input. Prefer normalized proximity for cross-bin comparisons.
proximity_col <- "ProximityFraction"
proximity_is_distance <- FALSE
contact_quantile <- 0.75

# For dyadic RFID-derived contact fractions, a positive Weight means at least
# some same-position contact in the bin. Set FALSE for quantile-thresholded edges.
use_positive_dyad_weight <- TRUE

# ------------------------------------------------
# LOAD ANIMAL-LEVEL DATA
# ------------------------------------------------

raw_dat <- read_behavior_table(input_file)
if (!proximity_col %in% names(raw_dat)) proximity_col <- "Proximity"
behav <- standardize_behavior_columns(raw_dat, proximity_col = proximity_col)

ensure_dir(output_dir)
ensure_dir(file.path(output_dir, "tables"))
ensure_dir(file.path(output_dir, "figures"))

# ------------------------------------------------
# ANIMAL-LEVEL SOCIAL CONNECTEDNESS / FRAGMENTATION
# ------------------------------------------------

contact_threshold <- if (proximity_is_distance) {
  quantile(behav$Proximity, probs = 1 - contact_quantile, na.rm = TRUE)
} else {
  quantile(behav$Proximity, probs = contact_quantile, na.rm = TRUE)
}

animal_social <- behav %>%
  mutate(
    social_contact_bin = if (proximity_is_distance) Proximity <= contact_threshold else Proximity >= contact_threshold,
    Proximity_z = z_within_metric(Proximity),
    Movement_z = z_within_metric(Movement),
    Entropy_z = z_within_metric(Entropy),
    ActiveIsolation = -Proximity_z + Movement_z,
    PassiveIsolation = -Proximity_z - Movement_z,
    SocialEngagement = Proximity_z + Movement_z,
    BinLevel = bin_level,
    ProximityInput = proximity_col
  ) %>%
  group_by(BinLevel, ProximityInput, Group, Sex, Phase, CageChange, AnimalNum) %>%
  arrange(TimeIndex, .by_group = TRUE) %>%
  summarise(
    mean_proximity = mean(Proximity, na.rm = TRUE),
    proximity_rmssd = calc_rmssd(Proximity),
    proximity_acf1 = calc_acf1(Proximity),
    contact_fraction = mean(social_contact_bin, na.rm = TRUE),
    contact_switch_rate = mean(social_contact_bin != lag(social_contact_bin), na.rm = TRUE),
    active_isolation = mean(ActiveIsolation, na.rm = TRUE),
    passive_isolation = mean(PassiveIsolation, na.rm = TRUE),
    social_engagement = mean(SocialEngagement, na.rm = TRUE),
    n_bins = n(),
    .groups = "drop"
  )

write_table(animal_social, file.path(output_dir, "tables", "animal_level_social_dynamics.csv"))

p_social <- animal_social %>%
  pivot_longer(
    cols = c(contact_fraction, contact_switch_rate, active_isolation, passive_isolation, social_engagement),
    names_to = "Metric",
    values_to = "Value"
  ) %>%
  ggplot(aes(Group, Value, fill = Group)) +
  geom_violin(alpha = 0.5, linewidth = 0.2, trim = FALSE) +
  geom_jitter(width = 0.1, size = 0.8, alpha = 0.7) +
  facet_grid(Metric ~ Phase, scales = "free_y") +
  labs(
    title = "Animal-level social dynamics",
    subtitle = paste0("Bin level: ", bin_level, "; proximity input: ", proximity_col),
    x = NULL,
    y = NULL
  ) +
  make_nature_theme()

save_plot_svg_pdf(p_social, file.path(output_dir, "figures", "animal_level_social_dynamics"), width = 180, height = 140)

# ------------------------------------------------
# TRUE DYADIC GRAPH ANALYSIS IF DYAD FILE EXISTS
# ------------------------------------------------

if (!is.null(dyad_file) && file.exists(dyad_file)) {
  message("Using dyadic RFID contact file: ", dyad_file)

  dyad_raw <- read_behavior_table(dyad_file)

  focal_col <- first_existing_col(dyad_raw, c("Focal", "AnimalNum", "Animal", "MouseID", "animal_1", "id1"), TRUE, "dyad focal column")
  partner_col <- first_existing_col(dyad_raw, c("Partner", "OtherAnimal", "PartnerID", "animal_2", "id2"), TRUE, "dyad partner column")
  time_col <- first_existing_col(dyad_raw, c("TimeIndex", "HalfHourElapsed", "HalfHourWithinCC0", "HalfHour", "Time", "TimeBin", "datetime", "DateTime"), TRUE, "dyad time column")
  prox_col <- first_existing_col(dyad_raw, c("Weight", "ProximityFraction", "Proximity", "proximity", "contact_fraction", "same_position_fraction", "Distance", "distance", "Interaction", "interaction_weight"), TRUE, "dyad proximity column")
  group_col <- first_existing_col(dyad_raw, c("Group", "Phenotype", "Condition", "Treatment", "StressGroup"), FALSE, "dyad group column")
  sex_col <- first_existing_col(dyad_raw, c("Sex", "sex"), FALSE, "dyad sex column")
  phase_col <- first_existing_col(dyad_raw, c("Phase", "phase", "LightDark", "DayNight"), FALSE, "dyad phase column")
  cage_col <- first_existing_col(dyad_raw, c("CageChange", "CC", "CageChangeNum", "Regrouping", "Batch", "Cage"), FALSE, "dyad cage-change column")
  batch_col <- first_existing_col(dyad_raw, c("Batch", "batch"), FALSE, "dyad batch column")
  system_col <- first_existing_col(dyad_raw, c("System", "system", "Cage", "cage"), FALSE, "dyad system column")
  observed_col <- first_existing_col(dyad_raw, c("observation_seconds", "ObservationSeconds", "duration", "DurationSec"), FALSE, "dyad observation seconds column")

  dyad <- dyad_raw %>%
    transmute(
      Focal = as.character(.data[[focal_col]]),
      Partner = as.character(.data[[partner_col]]),
      TimeIndex = .data[[time_col]],
      Weight = suppressWarnings(as.numeric(.data[[prox_col]])),
      Group = if (!is.na(group_col)) as.factor(.data[[group_col]]) else factor("All"),
      Sex = if (!is.na(sex_col)) as.factor(.data[[sex_col]]) else factor("All"),
      Phase = if (!is.na(phase_col)) as.factor(.data[[phase_col]]) else factor("All"),
      CageChange = if (!is.na(cage_col)) as.factor(.data[[cage_col]]) else factor("All"),
      Batch = if (!is.na(batch_col)) as.factor(.data[[batch_col]]) else factor("All"),
      System = if (!is.na(system_col)) as.factor(.data[[system_col]]) else factor("All"),
      observation_seconds = if (!is.na(observed_col)) suppressWarnings(as.numeric(.data[[observed_col]])) else NA_real_,
      BinLevel = bin_level,
      DyadWeightInput = prox_col
    ) %>%
    filter(!is.na(Focal), !is.na(Partner), Focal != Partner, is.finite(Weight))

  if (nrow(dyad) == 0) {
    warning("Dyadic file was found, but no valid dyadic rows remained after filtering.")
  } else {
    threshold <- if (use_positive_dyad_weight) {
      0
    } else if (proximity_is_distance) {
      quantile(dyad$Weight, probs = 1 - contact_quantile, na.rm = TRUE)
    } else {
      quantile(dyad$Weight, probs = contact_quantile, na.rm = TRUE)
    }

    edge_tbl <- dyad %>%
      mutate(
        Contact = if (use_positive_dyad_weight) {
          Weight > 0
        } else if (proximity_is_distance) {
          Weight <= threshold
        } else {
          Weight >= threshold
        }
      )

    write_table(edge_tbl, file.path(output_dir, "tables", "dyadic_edges_network_input.csv"))

    dyad_summary <- edge_tbl %>%
      group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, Batch, System, Focal, Partner) %>%
      summarise(
        mean_weight = mean(Weight, na.rm = TRUE),
        median_weight = median(Weight, na.rm = TRUE),
        contact_bin_fraction = mean(Contact, na.rm = TRUE),
        total_observation_seconds = sum(observation_seconds, na.rm = TRUE),
        n_bins = n(),
        .groups = "drop"
      )

    write_table(dyad_summary, file.path(output_dir, "tables", "dyadic_pair_summary.csv"))

    if (requireNamespace("igraph", quietly = TRUE)) {
      graph_metrics <- edge_tbl %>%
        group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, Batch, System, TimeIndex) %>%
        group_modify(~{
          edges <- .x %>% filter(Contact) %>% select(Focal, Partner, Weight)
          nodes <- unique(c(.x$Focal, .x$Partner))
          if (length(nodes) < 2 || nrow(edges) == 0) {
            return(tibble(
              n_nodes = length(nodes), n_edges = 0, density = 0, modularity = NA_real_,
              mean_degree = 0, mean_strength = 0, clustering = NA_real_,
              components = length(nodes),
              largest_component_fraction = ifelse(length(nodes) > 0, 1 / length(nodes), NA_real_)
            ))
          }
          g <- igraph::graph_from_data_frame(edges, directed = FALSE, vertices = tibble(name = nodes))
          comps <- igraph::components(g)
          tibble(
            n_nodes = igraph::vcount(g),
            n_edges = igraph::ecount(g),
            density = igraph::edge_density(g, loops = FALSE),
            modularity = ifelse(igraph::ecount(g) > 0, igraph::modularity(igraph::cluster_louvain(g)), NA_real_),
            mean_degree = mean(igraph::degree(g), na.rm = TRUE),
            mean_strength = mean(igraph::strength(g, weights = igraph::E(g)$Weight), na.rm = TRUE),
            clustering = suppressWarnings(igraph::transitivity(g, type = "average", isolates = "zero")),
            components = comps$no,
            largest_component_fraction = max(comps$csize, na.rm = TRUE) / igraph::vcount(g)
          )
        }) %>%
        ungroup()

      write_table(graph_metrics, file.path(output_dir, "tables", "dyadic_graph_metrics_by_time.csv"))

      node_metrics <- edge_tbl %>%
        group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, Batch, System, TimeIndex) %>%
        group_modify(~{
          edges <- .x %>% filter(Contact) %>% select(Focal, Partner, Weight)
          nodes <- unique(c(.x$Focal, .x$Partner))
          if (length(nodes) < 2 || nrow(edges) == 0) {
            return(tibble(AnimalNum = nodes, degree = 0, strength = 0, betweenness = NA_real_, closeness = NA_real_))
          }
          g <- igraph::graph_from_data_frame(edges, directed = FALSE, vertices = tibble(name = nodes))
          tibble(
            AnimalNum = igraph::V(g)$name,
            degree = igraph::degree(g),
            strength = igraph::strength(g, weights = igraph::E(g)$Weight),
            betweenness = igraph::betweenness(g, normalized = TRUE),
            closeness = suppressWarnings(igraph::closeness(g, normalized = TRUE))
          )
        }) %>%
        ungroup()

      write_table(node_metrics, file.path(output_dir, "tables", "dyadic_node_metrics_by_time.csv"))

      node_summary <- node_metrics %>%
        group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, Batch, System, AnimalNum) %>%
        summarise(
          mean_degree = mean(degree, na.rm = TRUE),
          mean_strength = mean(strength, na.rm = TRUE),
          mean_betweenness = mean(betweenness, na.rm = TRUE),
          mean_closeness = mean(closeness, na.rm = TRUE),
          degree_rmssd = calc_rmssd(degree),
          strength_rmssd = calc_rmssd(strength),
          n_time_bins = n(),
          .groups = "drop"
        )

      write_table(node_summary, file.path(output_dir, "tables", "dyadic_node_summary.csv"))

      p_density <- graph_metrics %>%
        ggplot(aes(TimeIndex, density, colour = Group)) +
        stat_summary(fun = mean, geom = "line", linewidth = 0.5) +
        facet_grid(Phase ~ CageChange, scales = "free_x") +
        labs(title = "Dynamic social-network density", subtitle = paste0("Bin level: ", bin_level), x = "Time bin", y = "Density") +
        make_nature_theme()

      save_plot_svg_pdf(p_density, file.path(output_dir, "figures", "dyadic_network_density_timecourse"), width = 180, height = 120)

      p_node <- node_summary %>%
        pivot_longer(cols = c(mean_degree, mean_strength, mean_betweenness, mean_closeness), names_to = "Metric", values_to = "Value") %>%
        ggplot(aes(Group, Value, fill = Group)) +
        geom_violin(alpha = 0.5, linewidth = 0.2, trim = FALSE) +
        geom_jitter(width = 0.1, size = 0.8, alpha = 0.7) +
        facet_grid(Metric ~ Phase, scales = "free_y") +
        labs(title = "Animal-level network centrality", subtitle = paste0("Bin level: ", bin_level), x = NULL, y = NULL) +
        make_nature_theme()

      save_plot_svg_pdf(p_node, file.path(output_dir, "figures", "dyadic_node_centrality_summary"), width = 180, height = 140)
    } else {
      message("Package igraph not installed. Dyadic table detected, but true graph metrics skipped.")
    }
  }
} else {
  message("No dyadic file found at: ", dyad_file)
  message("Run Analysis/05_build_dyadic_rfid_contacts.R first to enable true graph metrics.")
  message("Wrote animal-level social dynamics only.")
}

message("Dynamic social network analysis complete.")
