# ================================================================
# Dynamic Social Network Analysis
# MMMSociability
# ================================================================
# Goal:
#   Convert proximity / interaction data into time-resolved social-network
#   summaries suitable for stress-resilience analyses, with publication-
#   ready statistics, effect sizes, and figures.
#
# Two supported input formats:
#   A) animal-level table with normalized proximity per animal x time bin
#      -> estimates social connectedness / fragmentation per animal-period
#   B) dyadic table generated by Analysis/05_build_dyadic_rfid_contacts.R
#      -> computes true graph/network metrics
#
# Recommended scale:
#   1-5 min bins for dynamic networks. Default is 5min_based.
# ================================================================

suppressPackageStartupMessages({
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(readr)
  library(stringr)
  library(purrr)
  library(tibble)
})

source("C:/Users/topohl/Documents/GitHub/MMMSociability/Functions/behavioral_dynamics_helpers.R")
source("C:/Users/topohl/Documents/GitHub/MMMSociability/Functions/behavioral_dynamics_stats_helpers.R")
source("C:/Users/topohl/Documents/GitHub/MMMSociability/Functions/duration_normalization_helpers.R")

# ------------------------------------------------
# USER INPUT
# ------------------------------------------------

bin_level <- "5min_based"
input_file <- file.path("S:/Lab_Member/Tobi/Experiments/Exp9_Social-Stress/Analysis/Behavior/RFID/analysis_ready/03_derived_metrics", bin_level, "all_behavior_metrics.csv")
output_dir <- file.path("S:/Lab_Member/Tobi/Experiments/Exp9_Social-Stress/Analysis/Behavior/RFID/analysis_ready/06_behavioral_dynamics/social_networks", bin_level)

# True dyadic RFID contact file generated by Analysis/05_build_dyadic_rfid_contacts.R.
# This older dyadic file may not be multiscale unless that script was run with
# the corresponding bin size. If absent, animal-level social dynamics are still written.
dyad_file <- "S:/Lab_Member/Tobi/Experiments/Exp9_Social-Stress/Analysis/Behavior/RFID/analysis_ready/06_behavioral_dynamics/dyadic_contacts/tables/dyadic_network_ready.csv"

# Animal-level proximity input. Prefer normalized proximity for cross-bin comparisons.
proximity_col <- "ProximityFraction"
proximity_is_distance <- FALSE
contact_quantile <- 0.75

# For dyadic RFID-derived contact fractions, a positive Weight means at least
# some same-position contact in the bin. Set FALSE for quantile-thresholded edges.
use_positive_dyad_weight <- TRUE

group_colors <- c(
  "CON" = "#3d3b6e",
  "SUS" = "#e63947",
  "RES" = "#C6C3BB",
  "All" = "grey55"
)
group_levels <- c("CON", "RES", "SUS", "All")
pairwise_contrasts <- c("RES-CON", "SUS-CON", "SUS-RES")

animal_social_outcomes <- c(
  "mean_proximity", "proximity_rmssd", "proximity_acf1",
  "contact_fraction", "contact_switch_rate", "contact_entropy",
  "contact_switch_count_per_hour",
  "active_isolation", "passive_isolation", "social_engagement"
)

graph_outcomes <- c(
  "mean_density", "density_rmssd", "mean_edges", "mean_strength",
  "mean_clustering", "mean_modularity", "mean_components",
  "mean_largest_component_fraction", "fragmentation_index"
)

node_outcomes <- c(
  "mean_degree", "mean_strength", "mean_betweenness", "mean_closeness",
  "degree_rmssd", "strength_rmssd", "centrality_instability"
)

# ------------------------------------------------
# HELPERS
# ------------------------------------------------

parse_cage_change_index <- function(x) {
  idx <- suppressWarnings(as.integer(gsub("\\D+", "", as.character(x))))
  fallback <- match(as.character(x), sort(unique(as.character(x))))
  ifelse(is.na(idx), fallback, idx)
}

sig_from_p <- function(p) {
  case_when(
    is.na(p) ~ NA_character_,
    p < 0.001 ~ "***",
    p < 0.01 ~ "**",
    p < 0.05 ~ "*",
    p < 0.10 ~ "trend",
    TRUE ~ "ns"
  )
}

format_p_label <- function(p) {
  case_when(
    is.na(p) ~ NA_character_,
    p < 0.001 ~ "p<.001",
    TRUE ~ paste0("p=", sub("^0", "", formatC(p, format = "f", digits = 3)))
  )
}

add_stat_columns <- function(tbl) {
  if (nrow(tbl) == 0) return(tbl)
  tbl %>%
    mutate(
      ReportingP = p.adjust_bh_family,
      ReportingSignificance = sig_from_p(ReportingP),
      ReportingCorrection = "BH across all pairwise group contrasts",
      Significant = ReportingP < 0.05
    ) %>%
    select(-any_of(c("is_primary_contrast", "p.adjust_bh_primary", "p.sign_primary")))
}

write_stats_package <- function(dat, analysis_name, value_cols, by_cols, summary_group_cols) {
  summary_tbl <- make_dynamics_group_summary(dat, value_cols = value_cols, group_cols = summary_group_cols)
  contrast_tbl <- make_dynamics_group_contrasts(dat, value_cols = value_cols, by_cols = by_cols) %>%
    add_stat_columns()

  write_table(summary_tbl, file.path(output_dir, "stats_tables", paste0(analysis_name, "_group_summary.csv")))
  write_table(contrast_tbl, file.path(output_dir, "stats_tables", paste0(analysis_name, "_group_contrasts.csv")))

  invisible(list(summary = summary_tbl, contrasts = contrast_tbl))
}

make_publication_theme <- function(base_size = 7) {
  make_nature_theme(base_size = base_size) +
    theme(
      legend.position = "top",
      legend.key.width = unit(8, "mm"),
      panel.grid.major.y = element_line(linewidth = 0.15, colour = "grey92"),
      panel.grid.major.x = element_blank(),
      panel.spacing = unit(1.0, "lines"),
      plot.title = element_text(face = "bold", hjust = 0, size = base_size + 1),
      plot.subtitle = element_text(hjust = 0, size = base_size)
    )
}

summarise_mean_ci <- function(dat, value_col, group_cols) {
  dat %>%
    filter(is.finite(.data[[value_col]])) %>%
    group_by(across(all_of(group_cols))) %>%
    summarise(
      n_animals = n_distinct(AnimalNum),
      n_obs = n(),
      mean = mean(.data[[value_col]], na.rm = TRUE),
      sd = sd(.data[[value_col]], na.rm = TRUE),
      sem = sd / sqrt(n_obs),
      ci95 = 1.96 * sem,
      ymin = mean - ci95,
      ymax = mean + ci95,
      .groups = "drop"
    )
}

contact_entropy <- function(x) {
  p <- mean(x, na.rm = TRUE)
  if (!is.finite(p) || p <= 0 || p >= 1) return(0)
  -(p * log(p) + (1 - p) * log(1 - p))
}

make_pairwise_brackets <- function(data,
                                   contrast_tbl,
                                   outcome,
                                   facet_cols,
                                   value_col = "Value",
                                   p_threshold = 0.05,
                                   include_trends = FALSE) {
  empty_brackets <- tibble(
    contrast = character(), x_start = numeric(), x_end = numeric(),
    y = numeric(), y_tip = numeric(), label = character()
  )
  if (length(facet_cols) > 0) {
    for (nm in facet_cols) empty_brackets[[nm]] <- data[[nm]][0]
  }
  if (nrow(contrast_tbl) == 0 || !value_col %in% names(data)) return(empty_brackets)

  threshold <- if (include_trends) 0.10 else p_threshold

  brackets <- contrast_tbl %>%
    filter(
      Outcome == outcome,
      contrast %in% pairwise_contrasts,
      !is.na(ReportingP),
      ReportingP < threshold
    ) %>%
    mutate(
      x_start = match(group_ref, group_levels),
      x_end = match(group_comp, group_levels),
      label = format_p_label(ReportingP)
    ) %>%
    filter(is.finite(x_start), is.finite(x_end))

  if (nrow(brackets) == 0) return(empty_brackets)

  y_tbl <- data %>%
    group_by(across(all_of(facet_cols))) %>%
    summarise(
      y_max = max(.data[[value_col]], na.rm = TRUE),
      y_min = min(.data[[value_col]], na.rm = TRUE),
      .groups = "drop"
    ) %>%
    mutate(
      y_range = if_else(is.finite(y_max - y_min) & y_max > y_min, y_max - y_min, abs(y_max)),
      y_step = if_else(is.finite(y_range) & y_range > 0, 0.18 * y_range, 0.1),
      y_tip_size = 0.035 * y_step
    )

  brackets %>%
    group_by(across(all_of(facet_cols))) %>%
    arrange(ReportingP, .by_group = TRUE) %>%
    mutate(bracket_rank = row_number()) %>%
    ungroup() %>%
    left_join(y_tbl, by = facet_cols) %>%
    mutate(
      y = y_max + bracket_rank * y_step,
      y_tip = y - y_tip_size
    ) %>%
    select(any_of(facet_cols), contrast, x_start, x_end, y, y_tip, label, ReportingP, ReportingSignificance)
}

make_all_pairwise_brackets <- function(data, contrast_tbl, outcomes, facet_cols, value_col = "Value") {
  map_dfr(outcomes, function(outcome) {
    d <- data %>% filter(Outcome == outcome)
    make_pairwise_brackets(d, contrast_tbl, outcome = outcome, facet_cols = facet_cols, value_col = value_col) %>%
      mutate(Outcome = outcome)
  })
}

add_pairwise_brackets <- function(plot, bracket_tbl, text_size = 1.6) {
  if (nrow(bracket_tbl) == 0) return(plot)
  plot +
    geom_segment(
      data = bracket_tbl,
      aes(x = x_start, xend = x_end, y = y, yend = y),
      inherit.aes = FALSE,
      linewidth = 0.25
    ) +
    geom_segment(
      data = bracket_tbl,
      aes(x = x_start, xend = x_start, y = y, yend = y_tip),
      inherit.aes = FALSE,
      linewidth = 0.25
    ) +
    geom_segment(
      data = bracket_tbl,
      aes(x = x_end, xend = x_end, y = y, yend = y_tip),
      inherit.aes = FALSE,
      linewidth = 0.25
    ) +
    geom_text(
      data = bracket_tbl,
      aes(x = (x_start + x_end) / 2, y = y, label = label),
      inherit.aes = FALSE,
      vjust = -0.25,
      size = text_size
    )
}

make_effect_heatmap_data <- function(contrast_tbl, outcome_levels, label_map = NULL) {
  if (nrow(contrast_tbl) == 0 || !"contrast" %in% names(contrast_tbl)) {
    return(tibble(
      CagePhase = factor(),
      Outcome = factor(levels = outcome_levels),
      OutcomeLabel = character(),
      cohen_d = numeric(),
      SigLabel = character(),
      Sex = factor(),
      contrast = factor(levels = pairwise_contrasts)
    ))
  }
  out <- contrast_tbl %>%
    filter(contrast %in% pairwise_contrasts, status == "tested") %>%
    mutate(
      Outcome = factor(Outcome, levels = outcome_levels),
      CagePhase = paste(as.character(CageChange), Phase, sep = "\n"),
      CagePhase = factor(CagePhase, levels = unique(CagePhase[order(CageChange, Phase)])),
      contrast = factor(contrast, levels = pairwise_contrasts),
      SigLabel = if_else(ReportingP < 0.05, "*", "")
    )
  if (!is.null(label_map)) {
    out <- out %>% mutate(OutcomeLabel = recode(as.character(Outcome), !!!label_map, .default = as.character(Outcome)))
  } else {
    out <- out %>% mutate(OutcomeLabel = as.character(Outcome))
  }
  out
}

safe_graph_mean <- function(x) {
  if (all(!is.finite(x))) return(NA_real_)
  mean(x, na.rm = TRUE)
}

# ------------------------------------------------
# LOAD ANIMAL-LEVEL DATA
# ------------------------------------------------

raw_dat <- read_behavior_table(input_file)
if (!proximity_col %in% names(raw_dat)) proximity_col <- "Proximity"

behav <- standardize_behavior_columns(raw_dat, proximity_col = proximity_col) %>%
  mutate(
    Group = factor(as.character(Group), levels = unique(c(group_levels, sort(unique(as.character(Group)))))),
    CageChangeIndex = parse_cage_change_index(CageChange)
  )

ensure_dir(output_dir)
ensure_dir(file.path(output_dir, "tables"))
ensure_dir(file.path(output_dir, "stats_tables"))
ensure_dir(file.path(output_dir, "figures"))
output_dirs <- analysis_output_dirs(output_dir)
ensure_dir(file.path(output_dir, "figures", "publication"))
ensure_dir(file.path(output_dir, "figures", "publication", "overview"))
ensure_dir(file.path(output_dir, "figures", "publication", "panels"))
write_output_manifest(
  output_dir,
  script_name = "09_dynamic_social_networks.R",
  analysis_name = "dynamic social-network topology",
  primary_tables = c(
    "tables/animal_level_social_dynamics.csv",
    "tables/animal_level_social_threshold_sensitivity.csv",
    "tables/dyadic_pair_summary.csv",
    "tables/dyadic_partner_instability_jaccard.csv",
    "tables/dyadic_partner_threshold_sensitivity.csv",
    "tables/dyadic_node_summary.csv",
    "tables/dyadic_graph_period_summary.csv",
    "tables/social_reorganization_interpretation_guide.csv",
    "stats_tables/animal_social_dynamics_duration_sensitivity_group_contrasts.csv"
  ),
  primary_figures = c(
    "figures/publication/panels",
    "figures/publication/overview"
  ),
  notes = c("Separate social withdrawal, unstable engagement, and fragmented topology in reporting.")
)

epoch_duration_qc <- write_epoch_duration_qc(behav, output_dir, metric_source = "09_dynamic_social_networks", bin_size_sec = infer_bin_size_sec(behav))

# ------------------------------------------------
# ANIMAL-LEVEL SOCIAL CONNECTEDNESS / FRAGMENTATION
# ------------------------------------------------

contact_threshold <- if (proximity_is_distance) {
  quantile(behav$Proximity, probs = 1 - contact_quantile, na.rm = TRUE)
} else {
  quantile(behav$Proximity, probs = contact_quantile, na.rm = TRUE)
}

animal_threshold_tbl <- tibble(
  BinLevel = bin_level,
  ProximityInput = proximity_col,
  ProximityIsDistance = proximity_is_distance,
  ContactQuantile = contact_quantile,
  ContactThreshold = as.numeric(contact_threshold),
  n_rows = nrow(behav),
  n_animals = n_distinct(behav$AnimalNum)
)

write_table(animal_threshold_tbl, file.path(output_dir, "tables", "animal_level_contact_threshold.csv"))

threshold_sensitivity_grid <- c(0.60, 0.70, 0.75, 0.80)
animal_threshold_sensitivity <- map_dfr(threshold_sensitivity_grid, function(q) {
  thr <- if (proximity_is_distance) {
    quantile(behav$Proximity, probs = 1 - q, na.rm = TRUE)
  } else {
    quantile(behav$Proximity, probs = q, na.rm = TRUE)
  }
  behav %>%
    mutate(Contact = if (proximity_is_distance) Proximity <= thr else Proximity >= thr) %>%
    group_by(BinLevel = bin_level, ProximityInput = proximity_col, ContactQuantile = q, Group, Sex, Phase, CageChange, AnimalNum) %>%
    arrange(TimeIndex, .by_group = TRUE) %>%
    summarise(
      contact_fraction = mean(Contact, na.rm = TRUE),
      contact_switch_rate = if_else(n() >= 3, mean(Contact != lag(Contact), na.rm = TRUE), NA_real_),
      contact_entropy = contact_entropy(Contact),
      .groups = "drop"
    )
})
write_table(animal_threshold_sensitivity, file.path(output_dir, "tables", "animal_level_social_threshold_sensitivity.csv"))

animal_social <- behav %>%
  mutate(
    social_contact_bin = if (proximity_is_distance) Proximity <= contact_threshold else Proximity >= contact_threshold,
    Proximity_z = z_within_metric(Proximity),
    Movement_z = z_within_metric(Movement),
    Entropy_z = z_within_metric(Entropy),
    ActiveIsolation = -Proximity_z + Movement_z,
    PassiveIsolation = -Proximity_z - Movement_z,
    SocialEngagement = Proximity_z + Movement_z,
    BinLevel = bin_level,
    ProximityInput = proximity_col
  ) %>%
  group_by(BinLevel, ProximityInput, Group, Sex, Phase, CageChange, CageChangeIndex, AnimalNum) %>%
  arrange(TimeIndex, .by_group = TRUE) %>%
  summarise(
    mean_proximity = mean(Proximity, na.rm = TRUE),
    proximity_sd = sd(Proximity, na.rm = TRUE),
    proximity_rmssd = calc_rmssd(Proximity),
    proximity_acf1 = calc_acf1(Proximity),
    contact_fraction = mean(social_contact_bin, na.rm = TRUE),
    contact_switch_rate = if_else(n() >= 3, mean(social_contact_bin != lag(social_contact_bin), na.rm = TRUE), NA_real_),
    contact_switch_count = sum(social_contact_bin != lag(social_contact_bin), na.rm = TRUE),
    contact_entropy = contact_entropy(social_contact_bin),
    active_isolation = mean(ActiveIsolation, na.rm = TRUE),
    passive_isolation = mean(PassiveIsolation, na.rm = TRUE),
    social_engagement = mean(SocialEngagement, na.rm = TRUE),
    n_bins = n(),
    .groups = "drop"
  ) %>%
  join_duration_qc(epoch_duration_qc) %>%
  normalize_counts_to_rates(c("contact_switch_count"))

write_table(animal_social, file.path(output_dir, "tables", "animal_level_social_dynamics.csv"))
generate_duration_sensitivity_outputs(animal_social, epoch_duration_qc, output_dir, "animal_level_social_dynamics")

animal_stats <- write_stats_package(
  animal_social,
  analysis_name = "animal_level_social_dynamics",
  value_cols = animal_social_outcomes,
  by_cols = c("BinLevel", "ProximityInput", "Sex", "Phase", "CageChange"),
  summary_group_cols = c("BinLevel", "ProximityInput", "Sex", "Phase", "CageChange", "Group")
)
write_duration_sensitivity_statistics(
  animal_social,
  epoch_duration_qc,
  output_dir,
  analysis_name = "animal_level_social_dynamics",
  value_cols = animal_social_outcomes,
  by_cols = c("BinLevel", "ProximityInput", "Sex", "Phase", "CageChange"),
  summary_group_cols = c("BinLevel", "ProximityInput", "Sex", "Phase", "CageChange", "Group")
)

animal_social_long <- animal_social %>%
  pivot_longer(cols = all_of(animal_social_outcomes), names_to = "Outcome", values_to = "Value") %>%
  mutate(
    Outcome = factor(Outcome, levels = animal_social_outcomes),
    OutcomeLabel = recode(
      as.character(Outcome),
      mean_proximity = "Mean proximity",
      proximity_rmssd = "Proximity RMSSD",
      proximity_acf1 = "Proximity ACF1",
      contact_fraction = "Contact fraction",
      contact_switch_rate = "Contact switching",
      contact_switch_count_per_hour = "Contact switches/hour",
      contact_entropy = "Contact entropy",
      active_isolation = "Active isolation",
      passive_isolation = "Passive isolation",
      social_engagement = "Social engagement"
    )
  )

animal_brackets <- make_all_pairwise_brackets(
  animal_social_long,
  animal_stats$contrasts,
  outcomes = animal_social_outcomes,
  facet_cols = c("Sex", "Phase", "Outcome"),
  value_col = "Value"
)

p_social <- animal_social_long %>%
  filter(Outcome %in% c("contact_fraction", "contact_switch_rate", "active_isolation", "passive_isolation", "social_engagement")) %>%
  ggplot(aes(Group, Value, fill = Group)) +
  geom_violin(alpha = 0.55, linewidth = 0.25, trim = FALSE, colour = "grey25") +
  geom_jitter(width = 0.08, size = 0.75, alpha = 0.70, shape = 21, colour = "grey20", stroke = 0.12, show.legend = FALSE) +
  facet_grid(Sex + Phase ~ OutcomeLabel, scales = "free_y") +
  labs(
    title = "Animal-level social dynamics",
    subtitle = paste0("Bin level: ", bin_level, "; proximity input: ", proximity_col),
    x = NULL,
    y = NULL
  ) +
  scale_fill_manual(values = group_colors, drop = FALSE) +
  make_publication_theme(base_size = 6)

p_social <- add_pairwise_brackets(
  p_social,
  animal_brackets %>% filter(Outcome %in% c("contact_fraction", "contact_switch_rate", "active_isolation", "passive_isolation", "social_engagement")),
  text_size = 1.45
)

save_plot_svg_pdf(p_social, file.path(output_dir, "figures", "animal_level_social_dynamics"), width = 220, height = 145)

animal_trajectory_summary <- animal_social %>%
  pivot_longer(cols = c(contact_fraction, contact_switch_rate, social_engagement), names_to = "Outcome", values_to = "Value") %>%
  group_by(Group, Sex, Phase, CageChange, CageChangeIndex, Outcome) %>%
  summarise(
    n_animals = n_distinct(AnimalNum),
    n_obs = sum(is.finite(Value)),
    mean = mean(Value, na.rm = TRUE),
    sd = sd(Value, na.rm = TRUE),
    sem = sd / sqrt(n_obs),
    ci95 = 1.96 * sem,
    ymin = mean - ci95,
    ymax = mean + ci95,
    .groups = "drop"
  ) %>%
  mutate(
    CageChange = factor(as.character(CageChange), levels = unique(as.character(CageChange[order(CageChangeIndex)]))),
    OutcomeLabel = recode(Outcome, contact_fraction = "Contact fraction", contact_switch_rate = "Contact switching", social_engagement = "Social engagement")
  )

write_table(animal_trajectory_summary, file.path(output_dir, "tables", "animal_level_social_trajectory_summary.csv"))

p_social_traj <- ggplot(animal_trajectory_summary, aes(CageChange, mean, colour = Group, group = Group)) +
  geom_errorbar(aes(ymin = ymin, ymax = ymax), width = 0.08, linewidth = 0.28) +
  geom_line(linewidth = 0.55) +
  geom_point(aes(fill = Group), size = 1.45, shape = 21, stroke = 0.22) +
  facet_grid(Sex + Phase ~ OutcomeLabel, scales = "free_y") +
  labs(
    title = "Animal-level social dynamics across cage changes",
    subtitle = "Group mean +/- 95% CI",
    x = "Cage change",
    y = NULL
  ) +
  scale_colour_manual(values = group_colors, drop = FALSE) +
  scale_fill_manual(values = group_colors, drop = FALSE) +
  make_publication_theme(base_size = 6) +
  theme(axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1))

save_plot_svg_pdf(p_social_traj, file.path(output_dir, "figures", "animal_level_social_trajectories"), width = 190, height = 130)

animal_effect_tbl <- make_effect_heatmap_data(
  animal_stats$contrasts,
  outcome_levels = animal_social_outcomes,
  label_map = c(
    mean_proximity = "Mean proximity",
    proximity_rmssd = "Proximity RMSSD",
    proximity_acf1 = "Proximity ACF1",
    contact_fraction = "Contact fraction",
    contact_switch_rate = "Contact switching",
    contact_switch_count_per_hour = "Contact switches/hour",
    contact_entropy = "Contact entropy",
    active_isolation = "Active isolation",
    passive_isolation = "Passive isolation",
    social_engagement = "Social engagement"
  )
)

write_table(animal_effect_tbl, file.path(output_dir, "tables", "animal_level_social_effect_size_heatmap_data.csv"))

if (nrow(animal_effect_tbl) > 0) {
  p_animal_heat <- ggplot(animal_effect_tbl, aes(CagePhase, OutcomeLabel, fill = cohen_d)) +
    geom_tile(colour = "white", linewidth = 0.35) +
    geom_text(aes(label = SigLabel), size = 2.3, colour = "black") +
    facet_grid(Sex ~ contrast, scales = "free_x", space = "free_x") +
    labs(
      title = "Animal-level social dynamics effect-size map",
      subtitle = "Cohen's d for pairwise contrasts; asterisk marks BH-adjusted FDR < 0.05",
      x = NULL,
      y = NULL,
      fill = "Cohen's d"
    ) +
    scale_fill_gradient2(low = "#3d3b6e", mid = "white", high = "#e63947", midpoint = 0, na.value = "grey90") +
    make_publication_theme(base_size = 6) +
    theme(
      axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
      panel.grid = element_blank(),
      legend.position = "right"
    )

  save_plot_svg_pdf(p_animal_heat, file.path(output_dir, "figures", "publication", "overview", "animal_level_social_effect_size_heatmap"), width = 190, height = 150)
}

# ------------------------------------------------
# TRUE DYADIC GRAPH ANALYSIS IF DYAD FILE EXISTS
# ------------------------------------------------

if (!is.null(dyad_file) && file.exists(dyad_file)) {
  message("Using dyadic RFID contact file: ", dyad_file)

  dyad_raw <- read_behavior_table(dyad_file)

  focal_col <- first_existing_col(dyad_raw, c("Focal", "AnimalNum", "Animal", "MouseID", "animal_1", "id1"), TRUE, "dyad focal column")
  partner_col <- first_existing_col(dyad_raw, c("Partner", "OtherAnimal", "PartnerID", "animal_2", "id2"), TRUE, "dyad partner column")
  time_col <- first_existing_col(dyad_raw, c("TimeIndex", "HalfHourElapsed", "HalfHourWithinCC0", "HalfHour", "Time", "TimeBin", "datetime", "DateTime"), TRUE, "dyad time column")
  prox_col <- first_existing_col(dyad_raw, c("Weight", "ProximityFraction", "Proximity", "proximity", "contact_fraction", "same_position_fraction", "Distance", "distance", "Interaction", "interaction_weight"), TRUE, "dyad proximity column")
  group_col <- first_existing_col(dyad_raw, c("Group", "Phenotype", "Condition", "Treatment", "StressGroup"), FALSE, "dyad group column")
  sex_col <- first_existing_col(dyad_raw, c("Sex", "sex"), FALSE, "dyad sex column")
  phase_col <- first_existing_col(dyad_raw, c("Phase", "phase", "LightDark", "DayNight"), FALSE, "dyad phase column")
  cage_col <- first_existing_col(dyad_raw, c("CageChange", "CC", "CageChangeNum", "Regrouping", "Batch", "Cage"), FALSE, "dyad cage-change column")
  batch_col <- first_existing_col(dyad_raw, c("Batch", "batch"), FALSE, "dyad batch column")
  system_col <- first_existing_col(dyad_raw, c("System", "system", "Cage", "cage"), FALSE, "dyad system column")
  observed_col <- first_existing_col(dyad_raw, c("observation_seconds", "ObservationSeconds", "duration", "DurationSec"), FALSE, "dyad observation seconds column")

  dyad <- dyad_raw %>%
    transmute(
      Focal = as.character(.data[[focal_col]]),
      Partner = as.character(.data[[partner_col]]),
      TimeIndex = .data[[time_col]],
      Weight = suppressWarnings(as.numeric(.data[[prox_col]])),
      Group = if (!is.na(group_col)) as.factor(.data[[group_col]]) else factor("All"),
      Sex = if (!is.na(sex_col)) as.factor(.data[[sex_col]]) else factor("All"),
      Phase = if (!is.na(phase_col)) as.factor(.data[[phase_col]]) else factor("All"),
      CageChange = if (!is.na(cage_col)) as.factor(.data[[cage_col]]) else factor("All"),
      Batch = if (!is.na(batch_col)) as.factor(.data[[batch_col]]) else factor("All"),
      System = if (!is.na(system_col)) as.factor(.data[[system_col]]) else factor("All"),
      observation_seconds = if (!is.na(observed_col)) suppressWarnings(as.numeric(.data[[observed_col]])) else NA_real_,
      BinLevel = bin_level,
      DyadWeightInput = prox_col
    ) %>%
    filter(!is.na(Focal), !is.na(Partner), Focal != Partner, is.finite(Weight)) %>%
    mutate(
      Group = factor(as.character(Group), levels = unique(c(group_levels, sort(unique(as.character(Group)))))),
      CageChangeIndex = parse_cage_change_index(CageChange)
    )

  dyad_qc_tbl <- tibble(
    BinLevel = bin_level,
    DyadWeightInput = prox_col,
    n_rows_raw = nrow(dyad_raw),
    n_rows_valid = nrow(dyad),
    n_focal_animals = n_distinct(dyad$Focal),
    n_partner_animals = n_distinct(dyad$Partner),
    n_time_bins = n_distinct(dyad$TimeIndex),
    use_positive_dyad_weight = use_positive_dyad_weight
  )

  write_table(dyad_qc_tbl, file.path(output_dir, "tables", "dyadic_input_qc.csv"))

  if (nrow(dyad) == 0) {
    warning("Dyadic file was found, but no valid dyadic rows remained after filtering.")
  } else {
    threshold <- if (use_positive_dyad_weight) {
      0
    } else if (proximity_is_distance) {
      quantile(dyad$Weight, probs = 1 - contact_quantile, na.rm = TRUE)
    } else {
      quantile(dyad$Weight, probs = contact_quantile, na.rm = TRUE)
    }

    dyadic_threshold_tbl <- tibble(
      BinLevel = bin_level,
      DyadWeightInput = prox_col,
      ProximityIsDistance = proximity_is_distance,
      ContactQuantile = contact_quantile,
      UsePositiveDyadWeight = use_positive_dyad_weight,
      ContactThreshold = as.numeric(threshold)
    )
    write_table(dyadic_threshold_tbl, file.path(output_dir, "tables", "dyadic_contact_threshold.csv"))

    edge_tbl <- dyad %>%
      mutate(
        Contact = if (use_positive_dyad_weight) {
          Weight > 0
        } else if (proximity_is_distance) {
          Weight <= threshold
        } else {
          Weight >= threshold
        }
      )

    write_table(edge_tbl, file.path(output_dir, "tables", "dyadic_edges_network_input.csv"))

    dyadic_threshold_sensitivity <- map_dfr(threshold_sensitivity_grid, function(q) {
      thr <- if (use_positive_dyad_weight) {
        0
      } else if (proximity_is_distance) {
        quantile(dyad$Weight, probs = 1 - q, na.rm = TRUE)
      } else {
        quantile(dyad$Weight, probs = q, na.rm = TRUE)
      }
      dyad %>%
        mutate(Contact = if (use_positive_dyad_weight) Weight > 0 else if (proximity_is_distance) Weight <= thr else Weight >= thr) %>%
        group_by(BinLevel, DyadWeightInput, ContactQuantile = q, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System, Focal) %>%
        arrange(TimeIndex, Partner, .by_group = TRUE) %>%
        summarise(
          n_partners = n_distinct(Partner[Contact %in% TRUE]),
          partner_entropy = {
            partner_counts <- table(Partner[Contact %in% TRUE])
            p <- as.numeric(partner_counts) / sum(partner_counts)
            if (length(p) == 0 || !is.finite(sum(p))) NA_real_ else -sum(p * log2(p))
          },
          social_contact_fraction = mean(Contact, na.rm = TRUE),
          .groups = "drop"
        )
    })
    write_table(dyadic_threshold_sensitivity, file.path(output_dir, "tables", "dyadic_partner_threshold_sensitivity.csv"))

    dyad_summary <- edge_tbl %>%
      group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System, Focal, Partner) %>%
      summarise(
        mean_weight = mean(Weight, na.rm = TRUE),
        median_weight = median(Weight, na.rm = TRUE),
        max_weight = max(Weight, na.rm = TRUE),
        weight_rmssd = calc_rmssd(Weight),
        contact_bin_fraction = mean(Contact, na.rm = TRUE),
        total_observation_seconds = sum(observation_seconds, na.rm = TRUE),
        total_observation_hours = total_observation_seconds / 3600,
        contact_bins = sum(Contact, na.rm = TRUE),
        contact_bins_per_hour = if_else(is.finite(total_observation_hours) & total_observation_hours > 0,
                                        contact_bins / total_observation_hours, NA_real_),
        n_bins = n(),
        .groups = "drop"
      )

    write_table(dyad_summary, file.path(output_dir, "tables", "dyadic_pair_summary.csv"))

    dyad_preference <- dyad_summary %>%
      group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System, Focal) %>%
      mutate(
        total_weight = sum(mean_weight, na.rm = TRUE),
        partner_weight_share = if_else(total_weight > 0, mean_weight / total_weight, NA_real_)
      ) %>%
      summarise(
        AnimalNum = first(Focal),
        n_partners_observed = sum(mean_weight > 0, na.rm = TRUE),
        mean_partner_weight = mean(mean_weight, na.rm = TRUE),
        max_partner_weight = max(mean_weight, na.rm = TRUE),
        top_partner_share = max(partner_weight_share, na.rm = TRUE),
        partner_entropy = -sum(partner_weight_share * log(partner_weight_share + 1e-9), na.rm = TRUE),
        partner_evenness = partner_entropy / log(pmax(n(), 2)),
        mean_contact_bin_fraction = mean(contact_bin_fraction, na.rm = TRUE),
        .groups = "drop"
      )

    write_table(dyad_preference, file.path(output_dir, "tables", "dyadic_partner_preference_summary.csv"))

    dyadic_partner_instability <- edge_tbl %>%
      filter(Contact %in% TRUE) %>%
      group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System, Focal, TimeIndex) %>%
      summarise(partner_set = list(sort(unique(as.character(Partner)))), .groups = "drop") %>%
      arrange(Focal, CageChangeIndex, Phase, TimeIndex) %>%
      group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System, Focal) %>%
      mutate(
        prev_partner_set = lag(partner_set),
        jaccard_partner_similarity = map2_dbl(partner_set, prev_partner_set, function(a, b) {
          if (is.null(b) || length(b) == 0) return(NA_real_)
          union_n <- length(union(a, b))
          if (union_n == 0) return(NA_real_)
          length(intersect(a, b)) / union_n
        })
      ) %>%
      summarise(
        AnimalNum = first(Focal),
        mean_jaccard_partner_similarity = mean(jaccard_partner_similarity, na.rm = TRUE),
        partner_instability_index = 1 - mean_jaccard_partner_similarity,
        social_predictability = mean_jaccard_partner_similarity,
        .groups = "drop"
      )

    write_table(dyadic_partner_instability, file.path(output_dir, "tables", "dyadic_partner_instability_jaccard.csv"))

    preference_stats <- write_stats_package(
      dyad_preference,
      analysis_name = "dyadic_partner_preference",
      value_cols = c("n_partners_observed", "mean_partner_weight", "max_partner_weight", "top_partner_share", "partner_entropy", "partner_evenness", "mean_contact_bin_fraction"),
      by_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange"),
      summary_group_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange", "Group")
    )

    if (requireNamespace("igraph", quietly = TRUE)) {
      graph_metrics <- edge_tbl %>%
        group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System, TimeIndex) %>%
        group_modify(~{
          edges <- .x %>% filter(Contact) %>% select(Focal, Partner, Weight)
          nodes <- unique(c(.x$Focal, .x$Partner))
          if (length(nodes) < 2 || nrow(edges) == 0) {
            return(tibble(
              n_nodes = length(nodes), n_edges = 0, density = 0, modularity = NA_real_,
              mean_degree = 0, mean_strength = 0, clustering = NA_real_,
              components = length(nodes),
              largest_component_fraction = ifelse(length(nodes) > 0, 1 / length(nodes), NA_real_),
              fragmentation_index = ifelse(length(nodes) > 0, 1 - 1 / length(nodes), NA_real_)
            ))
          }
          g <- igraph::graph_from_data_frame(edges, directed = FALSE, vertices = tibble(name = nodes))
          comps <- igraph::components(g)
          tibble(
            n_nodes = igraph::vcount(g),
            n_edges = igraph::ecount(g),
            density = igraph::edge_density(g, loops = FALSE),
            modularity = ifelse(igraph::ecount(g) > 0, igraph::modularity(igraph::cluster_louvain(g)), NA_real_),
            mean_degree = mean(igraph::degree(g), na.rm = TRUE),
            mean_strength = mean(igraph::strength(g, weights = igraph::E(g)$Weight), na.rm = TRUE),
            clustering = suppressWarnings(igraph::transitivity(g, type = "average", isolates = "zero")),
            components = comps$no,
            largest_component_fraction = max(comps$csize, na.rm = TRUE) / igraph::vcount(g),
            fragmentation_index = 1 - max(comps$csize, na.rm = TRUE) / igraph::vcount(g)
          )
        }) %>%
        ungroup()

      write_table(graph_metrics, file.path(output_dir, "tables", "dyadic_graph_metrics_by_time.csv"))

      graph_period_summary <- graph_metrics %>%
        group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System) %>%
        arrange(TimeIndex, .by_group = TRUE) %>%
        summarise(
          mean_density = safe_graph_mean(density),
          density_rmssd = calc_rmssd(density),
          mean_edges = safe_graph_mean(n_edges),
          mean_strength = safe_graph_mean(mean_strength),
          mean_clustering = safe_graph_mean(clustering),
          mean_modularity = safe_graph_mean(modularity),
          mean_components = safe_graph_mean(components),
          mean_largest_component_fraction = safe_graph_mean(largest_component_fraction),
          fragmentation_index = safe_graph_mean(fragmentation_index),
          n_time_bins = n(),
          .groups = "drop"
        ) %>%
        mutate(n_time_bins_per_hour = if_else(is.finite(n_time_bins) & n_time_bins > 0, n_time_bins / pmax(n_time_bins * infer_bin_size_sec(.) / 3600, 1e-9), NA_real_))

      write_table(graph_period_summary, file.path(output_dir, "tables", "dyadic_graph_period_summary.csv"))

      graph_stats <- write_stats_package(
        graph_period_summary,
        analysis_name = "dyadic_graph_period",
        value_cols = graph_outcomes,
        by_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange"),
        summary_group_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange", "Group")
      )
      write_duration_sensitivity_statistics(
        graph_period_summary,
        epoch_duration_qc,
        output_dir,
        analysis_name = "dyadic_graph_period",
        value_cols = graph_outcomes,
        by_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange"),
        summary_group_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange", "Group"),
        join_by_cols = c("Group", "Sex", "CageChange", "Phase")
      )

      node_metrics <- edge_tbl %>%
        group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System, TimeIndex) %>%
        group_modify(~{
          edges <- .x %>% filter(Contact) %>% select(Focal, Partner, Weight)
          nodes <- unique(c(.x$Focal, .x$Partner))
          if (length(nodes) < 2 || nrow(edges) == 0) {
            return(tibble(AnimalNum = nodes, degree = 0, strength = 0, betweenness = NA_real_, closeness = NA_real_))
          }
          g <- igraph::graph_from_data_frame(edges, directed = FALSE, vertices = tibble(name = nodes))
          tibble(
            AnimalNum = igraph::V(g)$name,
            degree = igraph::degree(g),
            strength = igraph::strength(g, weights = igraph::E(g)$Weight),
            betweenness = igraph::betweenness(g, normalized = TRUE),
            closeness = suppressWarnings(igraph::closeness(g, normalized = TRUE))
          )
        }) %>%
        ungroup()

      write_table(node_metrics, file.path(output_dir, "tables", "dyadic_node_metrics_by_time.csv"))

      node_summary <- node_metrics %>%
        group_by(BinLevel, DyadWeightInput, Group, Sex, Phase, CageChange, CageChangeIndex, Batch, System, AnimalNum) %>%
        arrange(TimeIndex, .by_group = TRUE) %>%
        summarise(
          mean_degree = mean(degree, na.rm = TRUE),
          mean_strength = mean(strength, na.rm = TRUE),
          mean_betweenness = mean(betweenness, na.rm = TRUE),
          mean_closeness = mean(closeness, na.rm = TRUE),
          degree_rmssd = calc_rmssd(degree),
          strength_rmssd = calc_rmssd(strength),
          n_time_bins = n(),
          .groups = "drop"
        ) %>%
        mutate(
          centrality_instability = z_within_metric(degree_rmssd) + z_within_metric(strength_rmssd)
        )

      write_table(node_summary, file.path(output_dir, "tables", "dyadic_node_summary.csv"))

      node_stats <- write_stats_package(
        node_summary,
        analysis_name = "dyadic_node_centrality",
        value_cols = node_outcomes,
        by_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange"),
        summary_group_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange", "Group")
      )
      write_duration_sensitivity_statistics(
        node_summary,
        epoch_duration_qc,
        output_dir,
        analysis_name = "dyadic_node_centrality",
        value_cols = node_outcomes,
        by_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange"),
        summary_group_cols = c("BinLevel", "DyadWeightInput", "Sex", "Phase", "CageChange", "Group")
      )

      graph_time_summary <- graph_metrics %>%
        group_by(Group, Sex, Phase, CageChange, CageChangeIndex, TimeIndex) %>%
        summarise(
          n_obs = sum(is.finite(density)),
          mean_density = mean(density, na.rm = TRUE),
          sd_density = sd(density, na.rm = TRUE),
          sem_density = sd_density / sqrt(n_obs),
          ci95_density = 1.96 * sem_density,
          ymin = mean_density - ci95_density,
          ymax = mean_density + ci95_density,
          .groups = "drop"
        )

      write_table(graph_time_summary, file.path(output_dir, "tables", "dyadic_network_density_time_summary.csv"))

      p_density <- graph_time_summary %>%
        ggplot(aes(TimeIndex, mean_density, colour = Group, fill = Group)) +
        geom_ribbon(aes(ymin = ymin, ymax = ymax), alpha = 0.14, linewidth = 0) +
        geom_line(linewidth = 0.55) +
        facet_grid(Sex + Phase ~ CageChange, scales = "free_x") +
        labs(
          title = "Dynamic social-network density",
          subtitle = "Mean +/- 95% CI across network systems",
          x = "Time bin",
          y = "Density"
        ) +
        scale_colour_manual(values = group_colors, drop = FALSE) +
        scale_fill_manual(values = group_colors, drop = FALSE) +
        make_publication_theme(base_size = 6)

      save_plot_svg_pdf(p_density, file.path(output_dir, "figures", "dyadic_network_density_timecourse"), width = 210, height = 140)

      graph_long <- graph_period_summary %>%
        pivot_longer(cols = all_of(graph_outcomes), names_to = "Outcome", values_to = "Value") %>%
        mutate(
          Outcome = factor(Outcome, levels = graph_outcomes),
          OutcomeLabel = recode(
            as.character(Outcome),
            mean_density = "Mean density",
            density_rmssd = "Density RMSSD",
            mean_edges = "Mean edges",
            mean_strength = "Mean strength",
            mean_clustering = "Clustering",
            mean_modularity = "Modularity",
            mean_components = "Components",
            mean_largest_component_fraction = "Largest component",
            fragmentation_index = "Fragmentation"
          )
        )

      graph_brackets <- make_all_pairwise_brackets(
        graph_long,
        graph_stats$contrasts,
        outcomes = graph_outcomes,
        facet_cols = c("Sex", "Phase", "Outcome"),
        value_col = "Value"
      )

      p_graph <- graph_long %>%
        filter(Outcome %in% c("mean_density", "density_rmssd", "mean_clustering", "mean_modularity", "fragmentation_index")) %>%
        ggplot(aes(Group, Value, fill = Group)) +
        geom_violin(alpha = 0.55, linewidth = 0.25, trim = FALSE, colour = "grey25") +
        geom_jitter(width = 0.08, size = 0.75, alpha = 0.70, shape = 21, colour = "grey20", stroke = 0.12, show.legend = FALSE) +
        facet_grid(Sex + Phase ~ OutcomeLabel, scales = "free_y") +
        labs(
          title = "Dyadic graph-level social-network metrics",
          subtitle = paste0("Bin level: ", bin_level, "; dyad input: ", prox_col),
          x = NULL,
          y = NULL
        ) +
        scale_fill_manual(values = group_colors, drop = FALSE) +
        make_publication_theme(base_size = 6)

      p_graph <- add_pairwise_brackets(
        p_graph,
        graph_brackets %>% filter(Outcome %in% c("mean_density", "density_rmssd", "mean_clustering", "mean_modularity", "fragmentation_index")),
        text_size = 1.45
      )

      save_plot_svg_pdf(p_graph, file.path(output_dir, "figures", "dyadic_graph_period_summary"), width = 220, height = 145)

      node_long <- node_summary %>%
        pivot_longer(cols = all_of(node_outcomes), names_to = "Outcome", values_to = "Value") %>%
        mutate(
          Outcome = factor(Outcome, levels = node_outcomes),
          OutcomeLabel = recode(
            as.character(Outcome),
            mean_degree = "Degree",
            mean_strength = "Strength",
            mean_betweenness = "Betweenness",
            mean_closeness = "Closeness",
            degree_rmssd = "Degree RMSSD",
            strength_rmssd = "Strength RMSSD",
            centrality_instability = "Centrality instability"
          )
        )

      node_brackets <- make_all_pairwise_brackets(
        node_long,
        node_stats$contrasts,
        outcomes = node_outcomes,
        facet_cols = c("Sex", "Phase", "Outcome"),
        value_col = "Value"
      )

      p_node <- node_long %>%
        filter(Outcome %in% c("mean_degree", "mean_strength", "mean_betweenness", "degree_rmssd", "strength_rmssd")) %>%
        ggplot(aes(Group, Value, fill = Group)) +
        geom_violin(alpha = 0.55, linewidth = 0.25, trim = FALSE, colour = "grey25") +
        geom_jitter(width = 0.08, size = 0.75, alpha = 0.70, shape = 21, colour = "grey20", stroke = 0.12, show.legend = FALSE) +
        facet_grid(Sex + Phase ~ OutcomeLabel, scales = "free_y") +
        labs(title = "Animal-level network centrality", subtitle = paste0("Bin level: ", bin_level), x = NULL, y = NULL) +
        scale_fill_manual(values = group_colors, drop = FALSE) +
        make_publication_theme(base_size = 6)

      p_node <- add_pairwise_brackets(
        p_node,
        node_brackets %>% filter(Outcome %in% c("mean_degree", "mean_strength", "mean_betweenness", "degree_rmssd", "strength_rmssd")),
        text_size = 1.45
      )

      save_plot_svg_pdf(p_node, file.path(output_dir, "figures", "dyadic_node_centrality_summary"), width = 220, height = 145)

      graph_effect_tbl <- make_effect_heatmap_data(
        graph_stats$contrasts,
        outcome_levels = graph_outcomes,
        label_map = c(
          mean_density = "Density",
          density_rmssd = "Density RMSSD",
          mean_edges = "Edges",
          mean_strength = "Strength",
          mean_clustering = "Clustering",
          mean_modularity = "Modularity",
          mean_components = "Components",
          mean_largest_component_fraction = "Largest component",
          fragmentation_index = "Fragmentation"
        )
      )

      node_effect_tbl <- make_effect_heatmap_data(
        node_stats$contrasts,
        outcome_levels = node_outcomes,
        label_map = c(
          mean_degree = "Degree",
          mean_strength = "Strength",
          mean_betweenness = "Betweenness",
          mean_closeness = "Closeness",
          degree_rmssd = "Degree RMSSD",
          strength_rmssd = "Strength RMSSD",
          centrality_instability = "Centrality instability"
        )
      )

      write_table(graph_effect_tbl, file.path(output_dir, "tables", "dyadic_graph_effect_size_heatmap_data.csv"))
      write_table(node_effect_tbl, file.path(output_dir, "tables", "dyadic_node_effect_size_heatmap_data.csv"))

      if (nrow(graph_effect_tbl) > 0) {
        p_graph_heat <- ggplot(graph_effect_tbl, aes(CagePhase, OutcomeLabel, fill = cohen_d)) +
          geom_tile(colour = "white", linewidth = 0.35) +
          geom_text(aes(label = SigLabel), size = 2.3, colour = "black") +
          facet_grid(Sex ~ contrast, scales = "free_x", space = "free_x") +
          labs(
            title = "Dyadic graph metric effect-size map",
            subtitle = "Cohen's d for pairwise contrasts; asterisk marks BH-adjusted FDR < 0.05",
            x = NULL,
            y = NULL,
            fill = "Cohen's d"
          ) +
          scale_fill_gradient2(low = "#3d3b6e", mid = "white", high = "#e63947", midpoint = 0, na.value = "grey90") +
          make_publication_theme(base_size = 6) +
          theme(
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
            panel.grid = element_blank(),
            legend.position = "right"
          )

        save_plot_svg_pdf(p_graph_heat, file.path(output_dir, "figures", "publication", "overview", "dyadic_graph_effect_size_heatmap"), width = 190, height = 140)
      }

      if (nrow(node_effect_tbl) > 0) {
        p_node_heat <- ggplot(node_effect_tbl, aes(CagePhase, OutcomeLabel, fill = cohen_d)) +
          geom_tile(colour = "white", linewidth = 0.35) +
          geom_text(aes(label = SigLabel), size = 2.3, colour = "black") +
          facet_grid(Sex ~ contrast, scales = "free_x", space = "free_x") +
          labs(
            title = "Node centrality effect-size map",
            subtitle = "Cohen's d for pairwise contrasts; asterisk marks BH-adjusted FDR < 0.05",
            x = NULL,
            y = NULL,
            fill = "Cohen's d"
          ) +
          scale_fill_gradient2(low = "#3d3b6e", mid = "white", high = "#e63947", midpoint = 0, na.value = "grey90") +
          make_publication_theme(base_size = 6) +
          theme(
            axis.text.x = element_text(angle = 45, hjust = 1, vjust = 1),
            panel.grid = element_blank(),
            legend.position = "right"
          )

        save_plot_svg_pdf(p_node_heat, file.path(output_dir, "figures", "publication", "overview", "dyadic_node_effect_size_heatmap"), width = 190, height = 130)
      }

      preference_long <- dyad_preference %>%
        pivot_longer(
          cols = c(top_partner_share, partner_entropy, partner_evenness, mean_contact_bin_fraction),
          names_to = "Outcome",
          values_to = "Value"
        ) %>%
        mutate(
          Outcome = factor(Outcome, levels = c("top_partner_share", "partner_entropy", "partner_evenness", "mean_contact_bin_fraction")),
          OutcomeLabel = recode(Outcome, top_partner_share = "Top partner share", partner_entropy = "Partner entropy", partner_evenness = "Partner evenness", mean_contact_bin_fraction = "Contact fraction")
        )

      preference_brackets <- make_all_pairwise_brackets(
        preference_long,
        preference_stats$contrasts,
        outcomes = c("top_partner_share", "partner_entropy", "partner_evenness", "mean_contact_bin_fraction"),
        facet_cols = c("Sex", "Phase", "Outcome"),
        value_col = "Value"
      )

      p_preference <- preference_long %>%
        ggplot(aes(Group, Value, fill = Group)) +
        geom_violin(alpha = 0.55, linewidth = 0.25, trim = FALSE, colour = "grey25") +
        geom_jitter(width = 0.08, size = 0.75, alpha = 0.70, shape = 21, colour = "grey20", stroke = 0.12, show.legend = FALSE) +
        facet_grid(Sex + Phase ~ OutcomeLabel, scales = "free_y") +
        labs(
          title = "Dyadic partner preference structure",
          subtitle = "Animal-level concentration and evenness of partner weights",
          x = NULL,
          y = NULL
        ) +
        scale_fill_manual(values = group_colors, drop = FALSE) +
        make_publication_theme(base_size = 6)

      p_preference <- add_pairwise_brackets(p_preference, preference_brackets, text_size = 1.45)

      save_plot_svg_pdf(p_preference, file.path(output_dir, "figures", "dyadic_partner_preference_summary"), width = 200, height = 135)
    } else {
      message("Package igraph not installed. Dyadic table detected, but true graph metrics skipped.")
    }
  }
} else {
  message("No dyadic file found at: ", dyad_file)
  message("Run Analysis/05_build_dyadic_rfid_contacts.R first to enable true graph metrics.")
  message("Wrote animal-level social dynamics only.")
}

social_reorganization_interpretation_guide <- tibble(
  Construct = c("Proximity/co-occupancy proxy", "Partner instability", "Preferred-partner persistence", "Social fragmentation", "Phase-specific social organization", "Threshold sensitivity"),
  PrimaryOutputs = c(
    "animal_level_social_dynamics.csv",
    "dyadic_partner_instability_jaccard.csv",
    "dyadic_partner_preference_summary.csv",
    "dyadic_graph_period_summary.csv",
    "animal_level_social_dynamics.csv; dyadic_node_summary.csv",
    "animal_level_social_threshold_sensitivity.csv; dyadic_partner_threshold_sensitivity.csv"
  ),
  AllowedInterpretation = c(
    "Animal-level social engagement or withdrawal proxy.",
    "Turnover in the set of contact partners across time bins.",
    "Concentration of contact weight onto a top partner.",
    "Network-level separation into weaker or smaller connected components.",
    "Active-vs-inactive differences in social organization.",
    "Whether social findings depend on the edge/contact threshold."
  ),
  ReviewerRisk = c("medium", "medium", "medium", "high_if_dyadic_identity_unavailable", "medium", "low_when_direction_stable"),
  Caveat = c(
    "Do not call graph topology if only animal-level proximity is available.",
    "Requires dyadic identity.",
    "Requires dyadic identity.",
    "Requires true dyadic edges and sufficient animals per system.",
    "Interpret as behavioral phase structure, not circadian mechanism.",
    "Main claims should be robust across 0.60, 0.70, 0.75 and 0.80 thresholds."
  )
)

write_table(social_reorganization_interpretation_guide, file.path(output_dir, "tables", "social_reorganization_interpretation_guide.csv"))

message("Dynamic social network analysis complete. Animal-level and available dyadic network reports written.")
